# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Azure Login Test

on:
  push:
    branches:
      - 'building-and-testing-dotnet'

jobs:
  epic:
    name: One long epic job
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
    -
      name: 'Az CLI login'
      uses: azure/login@v1
      with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    - 
      name: 'Run Azure CLI commands'
      run: |
          az account show
          az group list
          pwd
