# TODO - Rename the file
name: Full Workflow

on:
  push:
    branches:
      - "building-and-testing-dotnet"

jobs:
  build-and-test:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    -
      run: "echo Would build"
    -
      run: "echo Would test"
  build-and-push-api:
    name: Build and push API
    uses: ./.github/workflows/build-and-push-acr.yml
    with:
      source-subfolder: WebApplication1
      netchris-app-aggregate: deleteme
      netchris-app-component: api
      netchris-app-environment: test
    secrets:
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_CONTAINER_REGISTRY_LOGIN_SERVER: ${{ secrets.ACR_LOGIN_SERVER_TEST }}
  # TODO - ...
  # build-and-push-app:
  #   name: Build and push app
  #   uses: ./.github/workflows/build-and-push-acr.yml
