name: caller

on:
  push:
    branches:
      - "building-and-testing-dotnet"

jobs:
  call-workflow-passing-data:
    uses: ./.github/workflows/called.yml@building-and-testing-dotnet
    with:
      config-path: .github/labeler.yml
    secrets:
      envPAT: ${{ secrets.envPAT }}
