name: Call Build and push to Azure Container Registry

#on: workflow_dispatch
on:
  push:
    branches:
      - 'building-and-testing-dotnet'

jobs:
  build-and-test:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    -
      run: "echo Would build"
    -
      run: "echo Would test"
      
  build-and-push-api:
    name: Build and push API
    permissions:
      id-token: write
      contents: read

    uses: ./.github/workflows/called.yml
  deploy-api:
    name: Deploy API
    needs: build-and-push-api
    runs-on: ubuntu-latest
    steps:
    -
      run: "echo Would deploy ${{ needs.build-and-push-api.outputs.PUBLISHED_DOCKER_IMAGE }}"
  # TODO - deploy-app
