name: container-image

on:
  push:
    branches:
      - "building-and-testing-dotnet"

# TODO - Reused workflow build-and-push
# - Returns (?) the pushed image (server/repo:tag)
# TODO - Reused deploy
# - Indicates pushed image
# - Target container app
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: test
    strategy:
      matrix:
        include:
          - 
            context-subfolder: WebApplication1
            imagetag: webapplication1
            container-app-name: app-deleteme-api
            resource-group: app-deleteme
          # - 
          #   context-subfolder: WebApplication2
          #   # TODO - WTF?  I can't push this until I set the container manually through the console.  Is there a setting I'm missing?
          #   imagetag: webapplication2
          #   container-app-name: aggregate-api
          #   resource-group: test20240106
    permissions:
      # Critical for Azure (https://paulyu.dev/article/pushing-multi-arch-container-images-guide/)
      id-token: write
      # Critical for Azure (https://paulyu.dev/article/pushing-multi-arch-container-images-guide/)
      contents: read
    env:
      DOCKER_IMAGE: ${{ secrets.ACR_LOGIN_SERVER_TEST }}/${{ matrix.imagetag }}:${{ github.sha }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: "Azure Login"
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          # TODO - This will obviously need to vary based on environment
          subscription-id: ${{ secrets.NC_AZURE_SUBSCRIPTION_ID_TESTING }}
      - name: Login to Azure Container Registry
        run: az acr login --name ${{ secrets.ACR_LOGIN_SERVER_TEST }}
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build "${{ matrix.context-subfolder }}" image and push to registry
        uses: docker/build-push-action@v5
        with:
          # This might be critical:
          # I want to build, publish, and dockerbuild only the app, not the whole solution.
          # So I ASSUME setting the context to the directory of the project will limit the
          # build scope to the csproj inside.
          context: "{{defaultContext}}:${{ matrix.context-subfolder }}"
          # Azure container apps are AMD64 so being explicit
          platforms: linux/amd64
          push: true
          tags: |
            ${{ env.DOCKER_IMAGE }}
          labels: |
            xxx1=yyy1
            xxx2=yyy2
            flerg=snett
      - name: Deploy Container App
        uses: azure/container-apps-deploy-action@v1
        with:
          imageToDeploy: ${{ env.DOCKER_IMAGE }}
          containerAppName: ${{ matrix.container-app-name }}
          resourceGroup: ${{ matrix.resource-group }}
